package com.github.vidaniello.amazon;
/**
 * <a href="https://developer-docs.amazon.com/sp-api/docs/feed-type-values">Amazon link site</a>
 * @author Vincenzo D'Aniello (vidaniello@gmail.com)
 *
 */
public enum AmazonSPAPIFeedTypeEnum{
	
//Listings feeds
JSON_LISTINGS_FEED,
POST_PRODUCT_DATA,
POST_INVENTORY_AVAILABILITY_DATA,
POST_PRODUCT_OVERRIDES_DATA,
POST_PRODUCT_PRICING_DATA,
POST_PRODUCT_IMAGE_DATA,
POST_PRODUCT_RELATIONSHIP_DATA,
POST_FLAT_FILE_INVLOADER_DATA,
POST_FLAT_FILE_LISTINGS_DATA,
POST_FLAT_FILE_BOOKLOADER_DATA,
POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA,
POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA,
POST_UIEE_BOOKLOADER_DATA,
POST_STD_ACES_DATA,

//Order feeds
POST_ORDER_ACKNOWLEDGEMENT_DATA,
POST_PAYMENT_ADJUSTMENT_DATA,
POST_ORDER_FULFILLMENT_DATA,
POST_INVOICE_CONFIRMATION_DATA,
POST_EXPECTED_SHIP_DATE_SOD,
POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA,
POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA,
POST_FLAT_FILE_FULFILLMENT_DATA,
POST_EXPECTED_SHIP_DATE_SOD_FLAT_FILE,

//Fulfillment by Amazon feeds
POST_FULFILLMENT_ORDER_REQUEST_DATA,
POST_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA,
POST_FBA_INBOUND_CARTON_CONTENTS,
POST_FLAT_FILE_FULFILLMENT_ORDER_REQUEST_DATA,
POST_FLAT_FILE_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA,
POST_FLAT_FILE_FBA_CREATE_INBOUND_PLAN,
POST_FLAT_FILE_FBA_UPDATE_INBOUND_PLAN,
POST_FLAT_FILE_FBA_CREATE_REMOVAL,

//Business feed
RFQ_UPLOAD_FEED,

//Easy Ship feed
POST_EASYSHIP_DOCUMENTS,

//Invoicing feed
UPLOAD_VAT_INVOICE
}
